/* HidzProject application security guard.
 *
 * The guard handles application-layer abuse only:
 * - suspicious injection / script payloads
 * - path traversal / command patterns
 * - request-rate abuse
 * - temporary IP blocks
 *
 * It deliberately does NOT treat CSP reports as attacks. CSP reports can be
 * generated by normal browser activity and are therefore kept separate.
 * Large volumetric DDoS traffic must still be filtered at the CDN/WAF edge.
 */
var crypto = require('crypto');
var db = require('./db');
var clientLocation = require('./ip-location');

var BLOCK_MS = 24 * 60 * 60 * 1000;
var MAX_BLOCK_MS = 7 * 24 * 60 * 60 * 1000;
var MAX_ALERT_TEXT = 180;

/* Conservative application-layer rate limit. It is intentionally below
   normal browser usage but high enough for normal page/API activity. */
var RATE_WINDOW_MS = 60 * 1000;
var RATE_MAX_REQUESTS = 90;
var RATE_BLOCK_MS = 10 * 60 * 1000;
var RATE_PATH = 'hidz_security_rate_limit';

/* Rentang IP resmi Cloudflare (sumber: https://www.cloudflare.com/ips/,
   per 28 Sep 2023) — cek ulang sesekali kalau Cloudflare umumin
   perubahan rentang. Dipakai supaya header CF-Connecting-IP cuma
   dipercaya kalau request itu memang lewat edge Cloudflare beneran. */
var CLOUDFLARE_CIDR_V4 = [
    ['173.245.48.0', 20], ['103.21.244.0', 22], ['103.22.200.0', 22],
    ['103.31.4.0', 22], ['141.101.64.0', 18], ['108.162.192.0', 18],
    ['190.93.240.0', 20], ['188.114.96.0', 20], ['197.234.240.0', 22],
    ['198.41.128.0', 17], ['162.158.0.0', 15], ['104.16.0.0', 13],
    ['104.24.0.0', 14], ['172.64.0.0', 13], ['131.0.72.0', 22]
];
var CLOUDFLARE_CIDR_V6 = [
    ['2400:cb00::', 32], ['2606:4700::', 32], ['2803:f800::', 32],
    ['2405:b500::', 32], ['2405:8100::', 32], ['2a06:98c0::', 29],
    ['2c0f:f248::', 32]
];

function ipv4ToInt(ip) {
    var parts = String(ip).split('.');
    if (parts.length !== 4) return null;
    var n = 0;
    for (var i = 0; i < 4; i++) {
        var octet = Number(parts[i]);
        if (!Number.isInteger(octet) || octet < 0 || octet > 255) return null;
        n = (n * 256) + octet;
    }
    return n >>> 0;
}

function ipv4InCidr(ip, base, bits) {
    var baseInt = ipv4ToInt(base);
    var ipInt = ipv4ToInt(ip);
    if (baseInt === null || ipInt === null) return false;
    var mask = bits === 0 ? 0 : (0xFFFFFFFF << (32 - bits)) >>> 0;
    return (ipInt & mask) === (baseInt & mask);
}

function ipv6ToBigInt(ip) {
    var groups;
    ip = String(ip);
    if (ip.indexOf('::') !== -1) {
        var halves = ip.split('::');
        if (halves.length > 2) return null;
        var head = halves[0] ? halves[0].split(':') : [];
        var tail = halves[1] ? halves[1].split(':') : [];
        var missing = 8 - (head.length + tail.length);
        if (missing < 0) return null;
        var fill = [];
        for (var i = 0; i < missing; i++) fill.push('0');
        groups = head.concat(fill).concat(tail);
    } else {
        groups = ip.split(':');
    }
    if (groups.length !== 8) return null;
    var value = 0n;
    for (var j = 0; j < 8; j++) {
        var g = groups[j] === '' ? 0 : parseInt(groups[j], 16);
        if (isNaN(g) || g < 0 || g > 0xFFFF) return null;
        value = (value << 16n) | BigInt(g);
    }
    return value;
}

function ipv6InCidr(ip, base, bits) {
    var baseVal = ipv6ToBigInt(base);
    var ipVal = ipv6ToBigInt(ip);
    if (baseVal === null || ipVal === null) return false;
    var full = (1n << 128n) - 1n;
    var mask = bits === 0 ? 0n : (full << BigInt(128 - bits)) & full;
    return (ipVal & mask) === (baseVal & mask);
}

/* True kalau ip itu memang bagian dari jaringan Cloudflare. */
function isCloudflareIp(ip) {
    if (!ip || ip === 'unknown') return false;
    var i;
    if (ip.indexOf(':') !== -1) {
        for (i = 0; i < CLOUDFLARE_CIDR_V6.length; i++) {
            if (ipv6InCidr(ip, CLOUDFLARE_CIDR_V6[i][0], CLOUDFLARE_CIDR_V6[i][1])) return true;
        }
        return false;
    }
    for (i = 0; i < CLOUDFLARE_CIDR_V4.length; i++) {
        if (ipv4InCidr(ip, CLOUDFLARE_CIDR_V4[i][0], CLOUDFLARE_CIDR_V4[i][1])) return true;
    }
    return false;
}

function clientIp(req) {
    var h = req.headers || {};
    var forwardedRaw = h['x-real-ip'] || h['x-forwarded-for'] || '';
    var trusted = String(forwardedRaw).split(',')[0].trim();
    if (!trusted && req.socket && req.socket.remoteAddress) trusted = req.socket.remoteAddress;
    if (!trusted) trusted = 'unknown';

    /* CF-Connecting-IP cuma header biasa di mata Vercel — TIDAK otomatis
       anti-spoofing kayak x-forwarded-for/x-real-ip (dua header itu selalu
       di-overwrite Vercel di edge, gak bisa dipalsukan client kecuali beli
       fitur Trusted Proxy). Jadi header ini cuma dipercaya kalau hop yang
       benar-benar nyambung ke Vercel (trusted, di atas) memang salah satu
       IP resmi Cloudflare — di luar itu, siapa pun bisa isi header ini
       sembarangan buat ngelewatin rate limit/IP block atau nge-fitnah IP
       orang lain. */
    var cfHeader = h['cf-connecting-ip'];
    if (cfHeader && isCloudflareIp(trusted)) {
        var cfIp = String(cfHeader).split(',')[0].trim();
        if (cfIp) return cfIp;
    }
    return trusted;
}

function ipKey(ip) {
    return crypto.createHash('sha256').update(String(ip)).digest('hex').slice(0, 48);
}

function sanitizeEndpoint(value) {
    var input = String(value || '').slice(0, 180);
    var hashIndex = input.indexOf('#');
    if (hashIndex !== -1) input = input.slice(0, hashIndex);

    var qIndex = input.indexOf('?');
    if (qIndex === -1) return input;

    var base = input.slice(0, qIndex);
    var query = input.slice(qIndex + 1);
    var sensitive = /^(?:password|pass|passwd|pwd|token|access_token|refresh_token|id_token|authorization|cookie|set-cookie|api[_-]?key|apikey|secret|credential|credentials|firebase_token|firebasetoken)$/i;

    var parts = query.split('&').map(function (part) {
        if (!part) return part;
        var eq = part.indexOf('=');
        var rawKey = eq === -1 ? part : part.slice(0, eq);
        var decodedKey = rawKey;
        try { decodedKey = decodeURIComponent(rawKey.replace(/\+/g, ' ')); } catch (e) {}
        if (sensitive.test(decodedKey)) return rawKey + '=[REDACTED]';
        return part.slice(0, 180);
    });

    return (base + '?' + parts.join('&')).slice(0, 180);
}

function textFromBody(body, out) {
    if (body == null) return;
    if (typeof body === 'string') {
        out.push(body);
        return;
    }
    if (typeof body !== 'object') return;

    Object.keys(body).forEach(function (k) {
        /* Never scan password values. A password is opaque data and should
           not be treated as an attack merely because it contains punctuation. */
        if (/password/i.test(k)) return;
        var v = body[k];
        if (typeof v === 'string' || typeof v === 'number') out.push(String(v));
        else if (v && typeof v === 'object') textFromBody(v, out);
    });
}

var SQLI = [
    /(?:union\s+(?:all\s+)?select)/i,
    /(?:or|and)\s+['"`]?\w+['"`]?\s*=\s*['"`]?\w+/i,
    /(?:sleep|benchmark|pg_sleep)\s*\(/i,
    /information_schema/i,
    /(?:load_file|into\s+outfile|xp_cmdshell)\s*\(/i,
    /(?:drop|truncate)\s+(?:table|database)\b/i
];

var WEB = [
    /<\s*(?:script|iframe|object|embed)\b/i,
    /<\s*(?:svg|img)\b[^>]*\bon\w+\s*=/i,
    /javascript\s*:/i,
    /document\.(?:body|documentElement)\.(?:innerHTML|outerHTML)/i,
    /(?:window\.)?eval\s*\(/i,
    /<\s*meta\b[^>]*http-equiv\s*=\s*["']?refresh/i
];

var PATH = [
    /\.\.\//,
    /%2e%2e(?:%2f|\/)/i,
    /(?:;|\||&&)\s*(?:cat|curl|wget|bash|sh|powershell|cmd)\b/i
];

function classify(req) {
    var pieces = [];
    textFromBody(req.body, pieces);
    pieces.push(req.url || '');

    var text = pieces.join('\n').slice(0, 12000);
    var i;

    for (i = 0; i < SQLI.length; i++) {
        if (SQLI[i].test(text)) return 'SQL injection pattern';
    }
    for (i = 0; i < WEB.length; i++) {
        if (WEB[i].test(text)) return 'script/defacement pattern';
    }
    for (i = 0; i < PATH.length; i++) {
        if (PATH[i].test(text)) return 'path traversal/command pattern';
    }
    return null;
}

async function isBlocked(ip) {
    var rec = await db.fetchPath('hidz_security_ip_blocks/' + ipKey(ip));
    if (!rec || !rec.blockedUntil) return false;

    if (Date.now() < Number(rec.blockedUntil)) return true;

    await db.deletePath('hidz_security_ip_blocks/' + ipKey(ip));
    return false;
}

async function writeEvent(req, reason, extra) {
    var ip = clientIp(req);
    var now = Date.now();
    var id = now + '_' + Math.random().toString(36).slice(2, 8);

    var event = {
        ip: ip,
        attemptAt: now,
        endpoint: sanitizeEndpoint(req.url),
        method: String(req.method || '').slice(0, 12),
        reason: String(reason || 'Suspicious request').slice(0, MAX_ALERT_TEXT),
        userAgent: String((req.headers && req.headers['user-agent']) || '').slice(0, 220),
        location: clientLocation(req)
    };

    if (extra && typeof extra === 'object') {
        Object.keys(extra).forEach(function (key) {
            event[key] = extra[key];
        });
    }

    await db.setPath('hidz_security_events/' + id, event);
    return event;
}

async function blockIp(req, reason, durationMs, tier) {
    var ip = clientIp(req);
    var key = ipKey(ip);
    var old = await db.fetchPath('hidz_security_ip_blocks/' + key);
    var oldTier = old && Number(old.tier) ? Number(old.tier) : 0;
    var nextTier = Math.max(oldTier, Number(tier) || 1);
    var duration = Math.min(Number(durationMs) || BLOCK_MS, MAX_BLOCK_MS);
    var now = Date.now();
    var blockedUntil = now + duration;

    await db.setPath('hidz_security_ip_blocks/' + key, {
        ip: ip,
        blocked: true,
        blockedAt: now,
        blockedUntil: blockedUntil,
        tier: nextTier,
        reason: String(reason || 'Suspicious request').slice(0, MAX_ALERT_TEXT),
        location: clientLocation(req)
    });

    await writeEvent(req, reason, {
        blockedUntil: blockedUntil,
        tier: nextTier
    });

    return { ip: ip, blockedUntil: blockedUntil };
}

async function checkRequestRate(req) {
    var ip = clientIp(req);
    var key = ipKey(ip);
    var path = RATE_PATH + '/' + key;
    var now = Date.now();
    var rec = await db.fetchPath(path);

    if (rec && rec.blockedUntil && now < Number(rec.blockedUntil)) {
        return { blocked: true, retryAfterSec: Math.ceil((Number(rec.blockedUntil) - now) / 1000) };
    }

    if (!rec || !rec.windowStarted || now - Number(rec.windowStarted) >= RATE_WINDOW_MS) {
        await db.setPath(path, { windowStarted: now, count: 1 });
        return { blocked: false };
    }

    var count = Number(rec.count || 0) + 1;
    if (count > RATE_MAX_REQUESTS) {
        var blockedUntil = now + RATE_BLOCK_MS;
        await db.setPath(path, {
            windowStarted: Number(rec.windowStarted),
            count: count,
            blockedUntil: blockedUntil
        });
        return {
            blocked: true,
            flood: true,
            retryAfterSec: Math.ceil(RATE_BLOCK_MS / 1000)
        };
    }

    await db.setPath(path, {
        windowStarted: Number(rec.windowStarted),
        count: count
    });
    return { blocked: false };
}

async function guard(req, res) {
    var ip = clientIp(req);

    try {
        if (await isBlocked(ip)) {
            res.status(403).json({ ok: false, error: 'Access denied' });
            return false;
        }

        var reason = classify(req);
        if (reason) {
            var old = await db.fetchPath('hidz_security_ip_blocks/' + ipKey(ip));
            var tier = old && Number(old.tier) ? Number(old.tier) + 1 : 1;
            var duration = Math.min(BLOCK_MS * Math.pow(2, Math.max(0, tier - 1)), MAX_BLOCK_MS);
            await blockIp(req, reason, duration, tier);
            res.status(403).json({ ok: false, error: 'Access denied' });
            return false;
        }

        var rate = await checkRequestRate(req);
        if (rate.blocked) {
            if (rate.flood) {
                await blockIp(req, 'Request flood / rate limit exceeded', RATE_BLOCK_MS, 1);
            }
            res.status(429).json({
                ok: false,
                error: 'Too many requests',
                retryAfterSec: rate.retryAfterSec
            });
            return false;
        }
    } catch (e) {
        /* Do not take the whole site offline when Firebase is temporarily
           unavailable. Edge/WAF protection remains independent of this guard. */
    }

    return true;
}

module.exports = {
    guard: guard,
    clientIp: clientIp,
    ipKey: ipKey,
    sanitizeEndpoint: sanitizeEndpoint
};
